hospital_project/hospital_project/urls.py
from django.contrib import admin
from django.urls import path

from hospital_site.views import patient, doctor, login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", login.login),
    path("enroll/", login.enroll),
    path("logout/", login.logout),
    
    path("patient/home/", patient.home),
    path("patient/register/", patient.register),
    path("patient/register/appoint/<int:doctor_id>/", patient.register_appoint),
    path("patient/register/success/", patient.register_sucess),
    path("patient/registrations/", patient.registrations),
    path("patient/cancel_registration/<int:registration_id>/", patient.cancel_registration),
    path("patient/personnel/", patient.personnel),
    path("patient/profile/<int:doctor_id>/", patient.profile),
    path('patient/medical_record/<int:registration_id>/', patient.medical_record),
    path('patient/personal/', patient.personal),

    path('doctor/home/', doctor.home),
    path('doctor/registrations/', doctor.registrations),
    path('doctor/medical_record/<int:registration_id>/', doctor.medical_record),
    path('doctor/accept/<int:registration_id>/', doctor.accept),
    path('doctor/finish/<int:registration_id>/', doctor.finish),
    path('doctor/medicine/', doctor.medicine),
    path('doctor/personal/', doctor.personal),
]

hospital_project/hospital_site/models.py
from django.db import models

class Patient(models.Model):
    '''患者'''
    name = models.CharField(verbose_name='姓名', max_length = 20)
    age = models.IntegerField(verbose_name='年龄', null=True, blank=True)
    username = models.CharField(verbose_name='用户名', max_length = 20, unique=True)
    password = models.CharField(verbose_name='密码', max_length = 20)
    GENDER_CHOICES = [
        (0, '男'),
        (1, '女'),
    ]
    gender = models.SmallIntegerField(verbose_name='性别', choices=GENDER_CHOICES, null=True, blank=True)

class Department(models.Model):
    '''科室'''
    name = models.CharField(verbose_name='科室名', max_length = 30)
    room_number = models.CharField(verbose_name='房间号', max_length = 20)

class Doctor(models.Model):
    '''医生'''
    name = models.CharField(verbose_name='姓名', max_length = 20)
    username = models.CharField(verbose_name='用户名', max_length = 20, unique=True)
    password = models.CharField(verbose_name='密码', max_length = 20)
    title = models.CharField(verbose_name='职称', max_length = 20)
    dept = models.ForeignKey(Department, verbose_name='科室', on_delete=models.CASCADE, related_name='doctors')
    profile = models.CharField(verbose_name='简介', max_length = 200)


class Registration(models.Model):
    '''挂号记录'''
    STATUS_CHOICES = [
        (0, '已挂号'),
        (1, '已取消'),
        (2, '就诊中'),
        (3, '就诊结束'),
    ]

    PERIOD_CHOICES = [
        (0, '8:00-10:00'),
        (1, '10:00-12:00'),
        (2, '14:00-16:00'),
        (3, '16:00-18:00'),
    ]

    doctor = models.ForeignKey(Doctor, verbose_name='医生', on_delete=models.CASCADE, related_name='registrations')
    patient = models.ForeignKey(Patient, verbose_name='患者', on_delete=models.CASCADE, related_name='appointments')
    registration_time = models.DateTimeField(verbose_name='挂号时间')
    period = models.SmallIntegerField(verbose_name='挂号时段', choices=PERIOD_CHOICES)
    status = models.SmallIntegerField(verbose_name='状态', choices=STATUS_CHOICES)

class MedicalRecord(models.Model):
    '''病历'''
    symptom = models.CharField(verbose_name='症状', max_length = 200)
    diagnosis = models.CharField(verbose_name='诊断结果', max_length = 200)
    solution = models.CharField(verbose_name='治疗方案', max_length = 200)
    registration = models.ForeignKey(Registration, verbose_name='预约信息', on_delete=models.CASCADE)


class Medicine(models.Model):
    '''药物'''
    TYPE_CHOICES = [
        (0, '中药'),
        (1, '西药'),
    ]

    name = models.CharField(verbose_name='名称', max_length = 30)
    type = models.SmallIntegerField(verbose_name='类型', choices=TYPE_CHOICES)
    producer = models.CharField(verbose_name='生产厂商', max_length = 30)
    price = models.DecimalField(verbose_name='价格', max_digits=5, decimal_places=2)

hospital_project/hospital_site/views/doctor.py
from django.shortcuts import render, redirect, get_object_or_404
from hospital_site.models import *
from django import forms
from django.core.paginator import Paginator

def home(request):
    return render(request, 'doctor/home.html')

def registrations(request):
    doctor_id = request.session.get('info')['id']
    doctor = Doctor.objects.get(id=doctor_id)
    registrations = Registration.objects.filter(doctor=doctor).order_by('registration_time', 'period')

    # 分页
    paginator = Paginator(registrations, 10)
    page_number = request.GET.get('page')
    registrations = paginator.get_page(page_number)

    return render(request, 'doctor/registrations.html', {'registrations': registrations})

class MedicalRecordForm(forms.ModelForm):
    class Meta:
        model = MedicalRecord
        exclude = ['registration']

def medical_record(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    
    try:
        medical_record = MedicalRecord.objects.get(registration=registration)
    except MedicalRecord.DoesNotExist:
        medical_record = None

    patient = registration.patient

    if request.method == 'GET':
        if medical_record == None:
            form = None
        else:
            form = MedicalRecordForm(instance=medical_record)
        return render(request, 'doctor/medical_record.html', {'form': form, 'patient': patient})

    form = MedicalRecordForm(request.POST, instance=medical_record)
    if form.is_valid():
        medical_record = form.save(commit=False)
        medical_record.registration = registration
        medical_record.save()
    return render(request, 'doctor/medical_record.html', {'form': form, 'patient': patient})
    
def accept(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    registration.status = 2
    registration.save()
    return redirect('/doctor/registrations')

def finish(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    registration.status = 3
    registration.save()
    return redirect('/doctor/registrations')

def medicine(request):
    medicines = Medicine.objects.all()
    types = Medicine.TYPE_CHOICES

    # 获取查询值
    name_query = request.GET.get('name', '')
    type_query = request.GET.get('type', '')
    
    if name_query:
        medicines = medicines.filter(name__contains=name_query)
    
    if type_query:
        medicines = medicines.filter(type=type_query)
    
    # 分页
    paginator = Paginator(medicines, 10)
    page_number = request.GET.get('page')
    medicines = paginator.get_page(page_number)

    # 转换为int在前端进行比较
    type_query = int(type_query, base=10) if type_query != '' else type_query
    
    return render(request, 'doctor/medicine.html', {'medicines': medicines, 'name_query': name_query, 'type_query': (type_query), 'types' : types})

def personal(request):
    doctor_id = request.session.get('info')['id']
    doctor = Doctor.objects.get(id=doctor_id)
    return render(request, 'doctor/personal.html', {'doctor': doctor})

hospital_project/hospital_site/views/login.py
from django.shortcuts import render, redirect, get_object_or_404

from hospital_site.models import Patient, Doctor
from django import forms
from django.core.validators import ValidationError

class LoginForm(forms.Form):
    username = forms.fields.CharField(
        required=True,
        label="用户名",
        widget=forms.widgets.TextInput({"placeholder":"请输入用户名","class":"form-control"})
    )
    password = forms.fields.CharField(
        required=True,
        label="密码",
        widget=forms.widgets.PasswordInput({"placeholder":"请输入密码","class":"form-control"})
    )

def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login/login.html", {"form": form})
    
    form = LoginForm(data=request.POST)
    if form.is_valid():
        login_type = request.POST.get('login_type')
        user_model = Patient if login_type == 'patient_login' else Doctor
        user = user_model.objects.filter(**form.cleaned_data).first()

        if user:
            # 验证成功，跳转到主页
            request.session["info"] = {'id': user.id, 'login_type': login_type}
            if login_type == 'patient_login':
                return redirect("/patient/home/")
            else:
                return redirect("/doctor/home/")    
        else:
            # 验证失败，增加错误并重新渲染
            form.add_error("password", "用户名或密码不正确")
            return render(request, "login/login.html", {"form": form})
    
    return render(request, "login/login.html", {"form": form})


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'age', 'username', 'password', 'gender']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        # 检查数据库中是否已经存在相同的用户名
        if Patient.objects.filter(username=username).exists():
            raise ValidationError("该用户名已被使用，请重新填写")
        return username
    
    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['username'].required = True
        self.fields['password'].required = True

def enroll(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save()
            return redirect('/login/')
    else:
        form = PatientForm()
    
    return render(request, "login/enroll.html", {"form": form})

def logout(request):
    request.session.clear()
    return redirect('/login/')

hospital_project/hospital_site/views/patient.py
from django.shortcuts import render, redirect, get_object_or_404

from hospital_site.models import *
from datetime import datetime
from django.core.paginator import Paginator

def home(request):
    return render(request, 'patient/home.html')

def register(request):
    doctors = Doctor.objects.all()
    departments = Department.objects.all()

    # 获取查询值
    name_query = request.GET.get('name', '')
    dept_query = request.GET.get('department', '')
    
    if name_query:
        doctors = doctors.filter(name__contains=name_query)
    
    if dept_query:
        doctors = doctors.filter(dept=dept_query)

    # 分页
    paginator = Paginator(doctors, 10)
    page_number = request.GET.get('page')
    doctors = paginator.get_page(page_number)

    # 转换为int在前端进行比较
    dept_query = int(dept_query, base=10) if dept_query != '' else dept_query
    
    return render(request, 'patient/register.html', {'doctors': doctors, 'name_query': name_query, 'dept_query': (dept_query), 'departments' : departments})
    
def register_sucess(request):
    return render(request, 'patient/register_success.html')

def register_appoint(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)

    if request.method == 'POST':
        appointment_time = request.POST.get('appointment_time')
        period = request.POST.get('period')

        # 将字符串时间转换为datetime对象
        appointment_datetime = datetime.strptime(appointment_time, '%Y-%m-%d')

        # 通过session获得患者实例
        patient = Patient.objects.get(id=request.session.get('info')['id'])

        # 创建挂号记录
        registration = Registration.objects.create(
            doctor=doctor,
            patient=patient,
            registration_time=appointment_datetime,
            period=period,
            status=0,
        )

        return redirect('/patient/register/success/')

    options = Registration.PERIOD_CHOICES
    return render(request, 'patient/register_appoint.html', {'doctor': doctor, 'options': options})

def registrations(request):
    patient_id = request.session.get('info')['id']
    patient = Patient.objects.get(id=patient_id)
    registrations = Registration.objects.filter(patient=patient)

    # 分页
    paginator = Paginator(registrations, 10)
    page_number = request.GET.get('page')
    registrations = paginator.get_page(page_number)

    return render(request, 'patient/registrations.html', {'registrations':registrations})

def cancel_registration(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    if registration.status == 0:
        registration.status = 1
        registration.save()
    
    return redirect('/patient/registrations/')


def personnel(request):
    doctors = Doctor.objects.all()
    departments = Department.objects.all()
    return render(request, 'patient/personnel.html', {'doctors': doctors, 'departments': departments})

def profile(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)
    return render(request, 'patient/profile.html', {'doctor': doctor})

def medical_record(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    medical_record = MedicalRecord.objects.get(registration=registration)
    return render(request, 'patient/medical_record.html', {'medical_record': medical_record})

def personal(request):
    patient_id = request.session.get('info')['id']
    patient = Patient.objects.get(id=patient_id)
    return render(request, 'patient/personal.html', {'patient': patient})

hospital_project/hospital_site/templates/patient/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>患者界面 - 首页</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">

    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css'%}">
    
    <style>
        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #a5bdd4;
          overflow: hidden;
      }


      .department-name {
          font-size: 1.2em;
          background-color: #a5bdd4; /* 设置科室名字背景颜色 */
          background: linear-gradient(to right, #a5bdd4 14%, transparent 14%);
          color: #fff; /* 设置科室名字文字颜色 */
          padding:3px; /* 设置内边距 */
          margin: 0px; /* 去除默认外边距 */
          white-space: nowrap; /* 防止科室名字换行 */
          margin-top: 20px;
      }

      .doctor-name {
          font-size: 1.4em;
          font-weight: bold;
          margin: 10px;/*可以修改名字之间的间距*/
          
      }

      .menu-container {
          flex-grow: 1; /* 让菜单栏和内容容器平分剩余空间 */
          align-items: flex-start;
      }
      .sidenav {    
          width: 200px;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          bottom:0;
          background-color: #0c1e35;
          padding-top: 20px;
          box-shadow: 2px 0 10px rgba(0, 0, 0, 0.1); /* 添加阴影效果 */
          margin-top: 0px; /* 调整上边距，将菜单栏下移 */
      }

      .sidenav a {
          padding: 9px 8px 8.7px 32px;
          text-decoration: none;
          font-size: 18px;
          color: #fff;
          display: block;
          margin-left: 10px;
          margin-bottom: 10px;

      }
      .sidenav a.active {
          color: #0c1e35;
          background-color: #fff;
      }
      .sidenav a:hover {
          color: #0c1e35;
          background-color: #fff;
      }
      .container {
          margin-left: 280px;
          height: 93vh; /* 设置容器的初始高度为视口的高度 */
          max-height: 93vh;
          overflow-y: auto; /* 添加滚动条，只在内容溢出时显示 */
          max-width: 140vh;
          position: relative;
          min-height: 90vh;
          background-color: #fff; /* 白色容器背景 */
          border-radius: 8px; /* 圆角边框 */
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 阴影效果 */
          flex-grow: 1;
          margin-right: 70px; 
          margin-top: 23px;
        }

        
      .hospital-info {
          margin: 0 auto;
          margin-top: 8px;
          padding: 20px;
          padding-top: 0px;
          background-color: #f8f8f8;
          border: 1px solid #ddd;
          border-radius: 8px;
      }
  
      .hospital-info h2 {
          color: #333;
      }
  
      .hospital-info p {
          color: #666;
      }
  
      .contact-info {
          margin-top: 15px;
      }
  
      .contact-info h4 {
          color: #333;
          margin-bottom: 8px;
      }
  
      .contact-info p {
          color: #666;
      }
      </style>
    </head>

<body>
    <!-- 菜单栏和页面内容容器 -->
    <div class="menu-container">
        <!-- 菜单栏 -->
        <div class="sidenav" style="bottom: 0;">
          <h5 style="color: #fff; margin: 30px; margin-top: 10.6px; font-size: 1.449em; letter-spacing: -0.2px;">患者界面</h5>
            <a href="/patient/home" class="active">首页</a>
            <a href="/patient/register" >预约挂号</a>
            <a href="/patient/personnel">医生介绍</a>
            <a href="/patient/registrations">挂号记录</a>
            <a href="/patient/personal" style="padding-top: 8px;">个人中心</a>
        </div>
        
<div class="container">
<!-- 医院简介 -->
<div class="hospital-info" >
  <h2>医院简介</h2>
  <p>我院拥有心血管内科、心血管外科、内分泌科、临床护理、呼吸内科、神经内科、眼科、肾病科、感染科、急诊科、医学影像科等国家临床重点专科建设项目11个，
    广东省临床重点学科18个，院士工作站5个，国家级培训中心17个，广东省质控、诊疗与研究中心42个。</p>
    <p>拥有高级职称专家720人，国管、省管专家62人，博士硕士导师142人，
    广东省学术技术带头人32人，国家级学术团体常委以上79人，广东省医学会专业分会主委、副主委116人。先后荣获国家自然科学基金等项目53项，省部级科研项目397项，
    获广东省科技进步一等奖2项。发表学术论文 3856 篇，其中SCI文章近300篇，中华核心400余篇。</p>
    <p>医院秉承“仁爱 博学 严谨 卓越”的医院精神，坚持“人民医院服务人民”的宗旨，始终服务在人民群众生命健康的前线。
    先后被评为全国百姓放心示范医院、全国卫生系统先进集体、全国医院文化建设先进单位、等荣誉称号。连续三届蝉联全国文明单位,
    连续8年荣获行风评议先进单位，被评为“人民群众满意医院”。</p>
 
  </p><hr>

    <div class="over_3">
        <h3 class="heading left-align">我们的服务</h3>
        <div class="line"></div>
        <div class="bak_7 clearfix">
            <div class="over_3a f_l bounceInLeft col-md-6 clearfix">
                <dl class="service-item">
                        <a  class="font-weight-bold" style="color: rgb(80, 163, 186) ;">
                            健康体检
                        </a>
                        <p>健康医学部2005年成立，于2012年9月17日搬入新门诊大楼9-11层，总面积达5400平方米。
                          配有专用通道、直达电梯，体检区域与门诊患者分开，
                          避免交叉感染。宽敞、明亮、整洁、现代化的体检大厅充分改善了体检者的受检环境。
                          医院聚集了大批临床经验丰富、专业知识渊博，工作严谨的医学人才。
                          在完成日常诊治的同时，轮流参加健康体检工作，为受检者提供高品质的体检服务</p>
                    </dd>
                </dl>
            </div>
            <div class="over_3a f_r bounceInRight col-md-6 clearfix">
              <dl class="service-item">               
                <a  class="font-weight-bold" style="color: rgb(80, 163, 186) ;">
                          远程医疗
                      </a>
                      <p>无论您身在何处，我们的远程医疗服务将为您提供方便快捷的医疗咨询和治疗选择。
                        您可以在家中与专业医生进行实时在线咨询，获取医学建议，甚至进行远程诊断。
                        我们的远程医疗团队由经验丰富的医生和护理人员组成，他们将倾听您的症状，提供专业的医学建议，并协助您进行治疗计划。
                        无论是常规的健康咨询、慢性病管理，还是急性病症的诊疗都能够满足您的需求。</p>
                      
                  </dd>
              </dl>
          </div>        
        <div class="bak_7 clearfix">
          <div class="over_3a f_l bounceInLeft col-md-6 clearfix">
              <dl class="service-item">
                <a  class="font-weight-bold" style="color: rgb(80, 163, 186) ;">
                          特色专科
                      </a>
                      <p>院区紧紧围绕妇科内分泌与生殖中心、整形美容外科、乳腺外科、口腔科四大特色专科及肿瘤内科、南院国际医疗部，
                        按照“人性化、国际化、市场化”的发展方向，努力打造全生命周期的一站式健康管理模式。</p>
                  </dd>
              </dl>
          </div>

          <div class="over_3a f_r bounceInRight col-md-6 clearfix">
            <dl class="service-item">               
              <a  class="font-weight-bold" style="color: rgb(80, 163, 186) ;">
                        专科专病
                    </a>
                    <p>我院专门开设了疑难病会诊中心，用来解决病情复杂、诊断困难的医学难题，为患者提供更深入、更专业的医学建议。
                      包括但不限于胰腺疾病疑难病会诊、胸部疾病疑难病会诊、炎性肠病疑难病会诊、垂体疾病疑难病会诊等。
                    </p>
                </dd>
            </dl>
        </div>
    </div>
      </div>
        </div><hr>
          <!-- 医院地址、邮箱、联系方式等信息 -->
  <div class="contact-info">
    <h4>联系我们：</h4>

        <p style="margin-left:19px ;"> 地址：广州市番禺区大学城至善医院</p>            
        <p style="margin-left:19px ;"> E-mail：info@example.com</p>
        <p style="margin-left:19px ;">电话总机：020-12345678</p>
    </div>
</div>
    </div>   
      </div>
    </div>  

</body>
</html>

hospital_project/hospital_site/templates/patient/personal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>患者界面 - 个人中心</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}"/>
  <style>
    /* 自定义样式 */
    body {
      height: 100%;
      background-color: #a5bdd4;
    }

    .patient-info-container {
      padding: 20px;
      margin: 20px;
      background-color: #f8f9fa;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      padding: 20px;
      max-width: 700px;
      margin: 80px auto;
    }

    /* 示例按钮样式 */
    .btn-primary {
        background-color: #98b0c6;
        border-color: #f8f9fa;
        margin-right: 20px;
        color: #f8f9fa;
    }

    .btn-primary:hover {
        background-color: #112434;
        border-color: #a5bdd4;
    }

    /* 样式类似于输入框 */
    .form-group {
      margin-bottom: 20px;
    }

    .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }

    .form-group p {
      padding: 8px 12px;
      border: 1px solid #ced4da;
      border-radius: 4px;
      background-color: #fff;
      margin: 0;
    }
  </style>
</head>
<body>

  <div class="container mt-5 patient-info-container">
    <h2 class="text-center">个人中心</h2>

    <div class="form-group">
      <label for="name">姓名: </label>
      <p>{{ patient.name }}</p>
    </div>

    <div class="form-group">
      <label for="username">用户名:</label>
      <p>{{ patient.username }}</p>
    </div>

    <div class="form-group">
      <label for="password">密码:</label>
      <p>{{ patient.password }}</p>
    </div>

    <div class="form-group">
      <label for="age">年龄:</label>
      <p>{{ patient.age }}</p>
    </div>

    <div class="form-group">
      <label for="gender">性别:</label>
      <p>{{ patient.get_gender_display }}</p>
    </div>
    
    <a href="#" class="btn btn-primary" onclick="goBack()">返回</a>
    <a href="/logout" class="btn btn-warning">注销</a>
  </div>
  <script>
        // JavaScript 函数，用于返回上一页
        function goBack() {
            window.history.back();
        }
  </script>
</body>
</html>

hospital_project/hospital_site/templates/patient/register_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>预约成功</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #fff;
      text-align: center;
      padding: 50px;
    }

    p {
      font-size: 24px;
      color: #333;
      margin-bottom: 20px;
    }

    a {
      display: inline-block;
      padding: 10px 20px;
      font-size: 18px;
      text-decoration: none;
      background-color: #a5bdd4;
      color: #fff;
      border-radius: 5px;
      transition: background-color 0.3s;
    }

    a:hover {
      background-color: #112434;
    }
  </style>
</head>
<body>
  <p>预约成功！</p>
  <a href="/patient/register/">返回主页</a>
</body>
</html>

hospital_project/hospital_site/templates/patient/registrations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>患者界面 - 挂号记录</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">
        <link rel="stylesheet" href="{% static 'css/doctor/registrations.css'%}">
        <link rel="stylesheet" href="{% static 'css/patient/registrations.css'%}">
        <link rel="stylesheet" href="/hospital/static/css/bootstrap/bootstrap.min.css"/>
        <link rel="stylesheet" href="/hospital/static/css/doctor/registrations.css"/>
        <link rel="stylesheet" href="/hospital/static/css/patient/registrations.css"/>
    </head>

<body>
    <!-- 菜单栏和页面内容容器 -->
    <div class="menu-container">
        <!-- 菜单栏 -->
        <div class="sidenav" >
            <h5 style="color: #fff; margin: 30px; margin-top: 10px;">患者界面</h5>
            <a href="/patient/home">首页</a>
            <a href="/patient/register">预约挂号</a>
            <a  href="/patient/personnel">医生介绍</a>
            <a class="active">挂号记录</a>
            <a href="/patient/personal">个人中心</a>
        </div>
        
        <div class="container" style="margin-top: 23px;">
            <table>
                <thead>
                  <tr>
                    <th>医生姓名</th>
                    <th>挂号时间</th>
                    <th>挂号时段</th>
                    <th>状态</th>
                    <th>操作</th>
                    <th>诊断结果</th>
                  </tr>
                </thead>
                    <tbody>
                    {% for registration in registrations %}
                        <tr>
                            <td>{{ registration.doctor.name }}</td>
                            <td>{{ registration.registration_time|date:"Y年m月d日" }}</td>
                            <td>{{ registration.get_period_display }}</td>
                            <td>{{ registration.get_status_display }}</td>

                            {% if registration.status == 0 %}
                            <td><a href="/patient/cancel_registration/{{ registration.id }}" style=" text-decoration: underline;">取消预约</a></td>
                            {% elif registration.status == 1 %}
                            <td>预约已取消</td>
                            {% else %}
                            <td></td>
                            {% endif %}
                            

                            {% if registration.status == 3 %}
                            <td><a href="/patient/medical_record/{{ registration.id }}" style=" text-decoration: underline;">查看详情</a></td>
                            {% else %}
                            <td></td>
                            {% endif %}

                        </tr>
                        {% endfor %}
                </tbody>
              </table>
            
            <div class="pagination">
                <span class="step-links">
                    {% if registrations.has_previous %}
                        <a href="?page=1">&laquo; 首页</a>
                        <a href="?page={{ registrations.previous_page_number }}">上一页</a>
                    {% else %}
                    <span class="step">
                    <a>&laquo; 首页</a>
                    <a>上一页</a></span>
                    {% endif %}
            
                    <span class="current">
                        第 {{ registrations.number }} / {{ registrations.paginator.num_pages }} 页
                    </span>
            
                    {% if registrations.has_next %}
                        <a href="?page={{ registrations.next_page_number }}">下一页</a>
                        <a href="?page={{ registrations.paginator.num_pages }}">尾页 &raquo;</a>
                    {% else %}
                    <span class="step">
                    <a>下一页</a>
                    <a>尾页 &raquo;</a></span>                 
                    {% endif %}
                </span>
            </div>
        </body>       
    </div>
    </div>  
</body>
</html>